[package]
name = "we-gui"
version = "0.2.7"
edition = "2021"

[dependencies]
dark-light = "1.1"
ctrlc = "3.4"
iced = { version = "0.14", features = ["tokio", "image", "svg"] }
image_rs = { package = "image", version = "0.25", default-features = false, features = ["gif"] }
html2text = "0.14"
resvg = "0.42"
rfd = "0.15"
serde_json = "1.0"
toml = "0.8"
tray-icon = "0.19"
we-core = { path = "../../crates/we-core" }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
